# frontend/Dockerfile.prod
# Build stage
FROM node:20-alpine as build-stage

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
# You can pass build arguments like VITE_API_URL here if needed
RUN npm run build

# Production stage
FROM nginx:alpine as production-stage
# Copy the build output to replace the default nginx contents.
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Run nginx
CMD ["nginx", "-g", "daemon off;"]
